name: work-flow
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the code
              uses: actions/checkout@v4
            - name: clean mvn
              run: mvn clean package